### ISSUE TITLE
Equation used in `is_patch_inside_FOV` function

### ISSUE THREAD

**Issue by jain-anshul** [orobix/retina-unet#19]
Can you please explain how did you reach to the following equation 

```x_ = x - int(img_w/2) # origin (0,0) shifted to image center \n
y_ = y - int(img_h/2)  # origin (0,0) shifted to image center
R_inside = 270 - int(patch_h*1.42) #radius is 270 (from DRIVE db docs), minus the patch diagonal (assumed it is a square #this is the limit to contain the full patch in the FOV
radius = np.sqrt((x_*x_)+(y_*y_))
```

According to me it the equation should be ```R_inside = 270 - int(patch_h/1.42) #Half of diagonal```

**Comment by lantiga** [comment]
Considering `patch_h` as the height of a patch in pixels, for a patch to be fully inside the FOV we consider the worst case scenario where a patch intersect the circle of the FOV (of radius 270) along the diagonal.

But you're right, we're being too conservative: we should be using half the diagonal since we're limiting the position of the center of the patch with respect to the center of the image. The correct equation should be `R_inside = 270 - int(patch_h / np.sqrt(2) * 2)`.

/cc @dcorti

**Comment by amitmanchanda1995** [comment]
@lantiga `R_inside = 270 - int(patch_h / np.sqrt(2) * 2)` is the same equation as used in the code. The correct equation, according to me, should be `R_inside = 270 - int(patch_h * np.sqrt(2) / 2)`

**Comment by lantiga** [comment]
My fix is dividing 1.42 by two, to get the coefficient by which you multiply the side of the patch to get the half normal, rather than the normal.
I'm not sure why you would rather divide by 1.42. Note that the result would be almost the same, since 1.42 / 2 ~ 1 / 1.42.

**Comment by lantiga** [comment]
Sorry, "half diagonal", not "half normal".

**Comment by dcorti** [comment]
Hi,

You're right, only half diagonal should be considered and not the full one. Your equation is correct, I updated the code. Thank you for spotting the mistake!

**Comment by lantiga** [comment]
Hey, so: I messed up. @amitmanchanda1995, of course you're right. I wrote:
> I'm not sure why you would rather divide by 1.42.
And that's exactly what I was doing in the equation, my bad. I apologize for the noise.

In any case, @dcorti, the right expression is:
```
R_inside = 270 - int(patch_h * np.sqrt(2) / 2).
```
