### ISSUE TITLE
Can't visit DRIVE website

### ISSUE THREAD

**Issue by Bonsen** [orobix/retina-unet#20]
I can't get data from http://www.isi.uu.nl/Research/Databases/DRIVE/ ....
If there any backup?

**Comment by dcorti** [comment]
It looks like the website is available again, I hope you can download the data now

**Comment by Bonsen** [comment]
@dcorti 
http://www.isi.uu.nl/Research/Databases/DRIVE/download.php 
it says:
Not Found

The requested URL /Research/Databases/DRIVE/process_download.php was not found on this server.

**Comment by pythonokai** [comment]
Hi, @Bonsen 
The flowing is that website said:
"DRIVE: Download
Here you can download all files in the DRIVE database. All files are contained in one zip file of approximately 30MB. The database includes:

The original JPEG compressed color photos in TIFF format.
The segmentations of both the first and second observer in GIF format.
Mask images which indicate the FOV in GIF format.

In order to verify the download we would like you to fill in a valid e-mail address. An e-mail from our system will be sent to this address within a few minutes. This e-mail contains a unique code which can be used on this page for downloading the database. Your e-mail will only be used for verification, we will not use the e-mail address in any other way."

hope that it can help you.

**Comment by Bonsen** [comment]
I mean when I clicked the "send mail"button on that page. Many days ago, I send a email to the website, and now they fix the page.
THANKS. @dcorti @pythonokai
